const fs = require('fs');

const tours = [
  {"ID_Tour": "TOUR_01", "Titulo": "Roma Barroca al Atardecer: Fuentes, Plazas & Secretos Papales", "Ciudad": "ROMA", "Duracion": "02:30 h", "Distancia": "3.8 km", "Ritmo": "Paseo Suave", "Link_Maps_Tramo_1": "https://www.google.com/maps/dir/?api=1&origin=Piazza+Barberini+Rome&destination=Fontana+di+Trevi+Rome&waypoints=Piazza+di+Spagna+Rome%7CScalinata+Trinita+dei+Monti%7CVia+Condotti+Rome%7CVia+delle+Muratte+Rome", "Link_Maps_Tramo_2": "https://www.google.com/maps/dir/?api=1&origin=Fontana+di+Trevi+Rome&destination=Piazza+Navona+Rome&waypoints=Galleria+Sciarra+Rome%7CChiesa+di+Sant%27Ignazio+di+Loyola+Rome%7CPiazza+di+Pietra+Rome%7CPantheon+Rome%7CChiesa+di+San+Luigi+dei+Francesi", "Tip_Ruta": "Hacerlo al caer el sol para ver las fuentes iluminadas y la perspectiva anamórfica de San Ignacio.", "Recomendacion_Veggie": "Giolitti (Via Uffici del Vicario 40) y pizza marinara caliente al corte en fornos tradicionales.", "Banos_WC": "Rinascente (Via del Tritone 61, piso 6, gratis e impecable) o cafeterías pidiendo espresso en barra."},
  {"ID_Tour": "TOUR_02", "Titulo": "Roma Medieval, Gueto Judío, Isla Tiberina & Trastevere", "Ciudad": "ROMA", "Duracion": "03:00 h", "Distancia": "4.5 km", "Ritmo": "Paseo Relajado", "Link_Maps_Tramo_1": "https://www.google.com/maps/dir/?api=1&origin=Campo+de%27+Fiori+Rome&destination=Ponte+Fabricio+Rome&waypoints=Piazza+Farnese+Rome%7CVia+Giulia+Rome%7CPiazza+Mattei+Rome%7CPortico+di+Ottavia+Rome%7CTeatro+di+Marcello+Rome", "Link_Maps_Tramo_2": "https://www.google.com/maps/dir/?api=1&origin=Ponte+Fabricio+Rome&destination=Piazza+di+Santa+Maria+in+Trastevere&waypoints=Isola+Tiberina+Rome%7CPonte+Cestio+Rome%7CPiazza+in+Piscinula+Rome%7CVia+della+Lungaretta+Rome%7CPiazza+Trilussa+Rome", "Tip_Ruta": "Ideal al atardecer: las luces doradas sobre el Tíber y el puente original más antiguo de Roma de 2000 años.", "Recomendacion_Veggie": "Pizzeria Da Remo o Dar Poeta (pizza marinara al horno de leña por 6-8 €) y carciofi alla giudia 100% vegetales en el Gueto.", "Banos_WC": "Bares históricos en Campo de' Fiori y trattorias en Trastevere."},
  {"ID_Tour": "TOUR_03", "Titulo": "Londres West End Teatral, Covent Garden & Chinatown", "Ciudad": "LONDRES", "Duracion": "02:30 h", "Distancia": "3.5 km", "Ritmo": "Paseo Urbano", "Link_Maps_Tramo_1": "https://www.google.com/maps/dir/?api=1&origin=Covent+Garden+Piazza+London&destination=Seven+Dials+London&waypoints=Jubilee+Market+Hall%7CSt+Paul%27s+Church+Covent+Garden%7CNeal%27s+Yard+London", "Link_Maps_Tramo_2": "https://www.google.com/maps/dir/?api=1&origin=Seven+Dials+London&destination=Leicester+Square+London&waypoints=Cambridge+Circus+London%7CPalace+Theatre+London%7CGerrard+Street+Chinatown%7CCecil+Court+London", "Tip_Ruta": "Buscar los callejones peatonales secretos de libros antiguos de Cecil Court.", "Recomendacion_Veggie": "Mildreds Soho (100% plant-based).", "Banos_WC": "Covent Garden Market."},
  {"ID_Tour": "TOUR_04", "Titulo": "Londres Real Monumental: Westminster, Whitehall & Buckingham", "Ciudad": "LONDRES", "Duracion": "02:45 h", "Distancia": "4.2 km", "Ritmo": "Paseo Escénico", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Estar a las 10:35 h frente a Victoria Memorial para ver el despliegue del Cambio de Guardia.", "Recomendacion_Veggie": "Meal Deals Plant Kitchen en Sainsbury's de Victoria Street o cafetería en St James's Park.", "Banos_WC": "Baños públicos de St James's Park (junto a Marlborough Gate) y estación Westminster."},
  {"ID_Tour": "TOUR_05", "Titulo": "Londres Ribereño, South Bank, Tate Modern & Tower Bridge", "Ciudad": "LONDRES", "Duracion": "03:15 h", "Distancia": "4.8 km", "Ritmo": "Ribereño Peatonal", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Paseo 100% peatonal junto al Támesis.", "Recomendacion_Veggie": "Borough Market: Bao buns veganos.", "Banos_WC": "Tate Modern."},
  {"ID_Tour": "TOUR_06", "Titulo": "La City Secreta: Callejones Romanos, St Dunstan & Leadenhall", "Ciudad": "LONDRES", "Duracion": "02:15 h", "Distancia": "3.2 km", "Ritmo": "Urbano Histórico", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "St Dunstan in the East es una iglesia gótica destruida reconvertida en jardín botánico secreto.", "Recomendacion_Veggie": "Pure en Fenchurch Street.", "Banos_WC": "Leadenhall Market o estación Monument."},
  {"ID_Tour": "TOUR_07", "Titulo": "Londres Soho, Carnaby Street, Regent Street & Mayfair", "Ciudad": "LONDRES", "Duracion": "02:00 h", "Distancia": "3.0 km", "Ritmo": "Paseo Comercial", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Entrar a Liberty London.", "Recomendacion_Veggie": "Kingly Court.", "Banos_WC": "Liberty London."},
  {"ID_Tour": "TOUR_08", "Titulo": "Notting Hill, Portobello Road, Casas Pastel & Love Actually", "Ciudad": "LONDRES", "Duracion": "02:30 h", "Distancia": "3.8 km", "Ritmo": "Paseo Pintoresco", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "St Luke's Mews tiene la famosa casa rosa del cartel de Love Actually.", "Recomendacion_Veggie": "Farmacy Notting Hill.", "Banos_WC": "Cafeterías en Portobello Road."},
  {"ID_Tour": "TOUR_09", "Titulo": "Camden Town, Regent's Canal, Mercados & Primrose Hill", "Ciudad": "LONDRES", "Duracion": "02:45 h", "Distancia": "4.2 km", "Ritmo": "Paseo Alternativo", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Caminar por el camino de sirga junto a las esclusas del canal hacia Primrose Hill.", "Recomendacion_Veggie": "Camden Lock Food Market.", "Banos_WC": "Stables Market."},
  {"ID_Tour": "TOUR_10", "Titulo": "Kensington Real: Freddie Mercury, Albertopolis & Hyde Park", "Ciudad": "LONDRES", "Duracion": "02:45 h", "Distancia": "4.5 km", "Ritmo": "Cultural y Verde", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Garden Lodge en Logan Place fue la residencia de Freddie Mercury.", "Recomendacion_Veggie": "Cafetería del V&A.", "Banos_WC": "V&A Museum."},
  {"ID_Tour": "TOUR_11", "Titulo": "St. Paul's Cathedral, Puente del Milenio & City de Londres", "Ciudad": "LONDRES", "Duracion": "02:00 h", "Distancia": "2.8 km", "Ritmo": "Ribereño Monumental", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Locación destruida por mortífagos.", "Recomendacion_Veggie": "Pret A Manger Veggie.", "Banos_WC": "Tate Modern."},
  {"ID_Tour": "TOUR_12", "Titulo": "Barcelona Passeig de Gràcia Modernista: Gaudí & Manzana de la Discordia", "Ciudad": "BARCELONA", "Duracion": "02:30 h", "Distancia": "3.6 km", "Ritmo": "Arquitectónico", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Pavimento hexagonal de Gaudí.", "Recomendacion_Veggie": "Teresa Carles.", "Banos_WC": "El Corte Inglés."},
  {"ID_Tour": "TOUR_13", "Titulo": "Barcelona Born, Ciutadella, Santa Maria del Mar & Barri Gòtic", "Ciudad": "BARCELONA", "Duracion": "03:15 h", "Distancia": "4.8 km", "Ritmo": "Histórico Medieval", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "El Pont del Bisbe tiene una calavera con daga oculta.", "Recomendacion_Veggie": "Rasoterra.", "Banos_WC": "El Born CCM."},
  {"ID_Tour": "TOUR_14", "Titulo": "Oxford Harry Potter, Universidades Históricas & Bodleian", "Ciudad": "OXFORD", "Duracion": "03:15 h", "Distancia": "4.2 km", "Ritmo": "Mágico y Universitario", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Christ Church y New College.", "Recomendacion_Veggie": "The Handle Bar.", "Banos_WC": "Oxford Covered Market."},
  {"ID_Tour": "TOUR_15", "Titulo": "Girona Medieval: Call Jueu, Juego de Tronos & Murallas", "Ciudad": "GIRONA", "Duracion": "03:30 h", "Distancia": "4.5 km", "Ritmo": "Histórico y Épico", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Escalinata del Gran Septo de Baelor.", "Recomendacion_Veggie": "Bionèctar.", "Banos_WC": "Baños Árabes."},
  {"ID_Tour": "TOUR_16", "Titulo": "Toledo Imperial: Senda del Tajo, Mirador del Valle & Fortaleza Targaryen", "Ciudad": "TOLEDO", "Duracion": "04:00 h", "Distancia": "5.8 km", "Ritmo": "Panorámico y Senderista", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Senda del Tajo y Mirador del Valle.", "Recomendacion_Veggie": "Mazapán Santo Tomé.", "Banos_WC": "Mirador del Valle."},
  {"ID_Tour": "TOUR_17", "Titulo": "Madrid de los Austrias, San Ginés, Sol & Palacio Real", "Ciudad": "MADRID", "Duracion": "02:30 h", "Distancia": "3.5 km", "Ritmo": "Histórico y Clásico", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "San Ginés y Palacio Real.", "Recomendacion_Veggie": "San Ginés.", "Banos_WC": "Mercado de San Miguel."},
  {"ID_Tour": "TOUR_18", "Titulo": "Madrid Retiro, Paisaje de la Luz, Prado & Templo de Debod", "Ciudad": "MADRID", "Duracion": "03:00 h", "Distancia": "4.5 km", "Ritmo": "Monumental y Verde", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Atardecer en Templo de Debod.", "Recomendacion_Veggie": "Levél Veggie Bistro.", "Banos_WC": "Prado."},
  {"ID_Tour": "TOUR_19", "Titulo": "Madrid Malasaña, Chueca & Gran Vía Bohemio", "Ciudad": "MADRID", "Duracion": "02:15 h", "Distancia": "3.2 km", "Ritmo": "Bohemio y Vanguardista", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Murales de Calle del Pez.", "Recomendacion_Veggie": "Distrito Vegano.", "Banos_WC": "Mercado San Antón."},
  {"ID_Tour": "TOUR_20", "Titulo": "Madrid Despedida: Jardines del Campo del Moro, Madrid Medieval & Santa Ana", "Ciudad": "MADRID", "Duracion": "02:30 h", "Distancia": "3.6 km", "Ritmo": "Señorial y Chill", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "Pavos reales en Campo del Moro.", "Recomendacion_Veggie": "Plaza Santa Ana.", "Banos_WC": "Campo del Moro."},
  {"ID_Tour": "TOUR_21", "Titulo": "Roma Trastevere Nocturno, Colina del Gianicolo & Fontana dell'Acqua Paola", "Ciudad": "ROMA", "Duracion": "02:45 h", "Distancia": "4.0 km", "Ritmo": "Bohemio y Panorámico", "Link_Maps_Tramo_1": "...", "Link_Maps_Tramo_2": "...", "Tip_Ruta": "La Gran Belleza en Fontana dell'Acqua Paola.", "Recomendacion_Veggie": "Tonnarello.", "Banos_WC": "Santa Maria in Trastevere."}
];

fs.writeFileSync('./tours_seed.json', JSON.stringify(tours));
console.log('Tours parsed');
